Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -60,7 +60,7 @@ jobs:
       - name: Run Tests and Generate Coverage
         run: |
           mkdir -p TestResults
-          cd AvansDevOpsTest && dotnet test --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=TestResults/coverage.cobertura.xml
+          cd AvansDevOpsTest && dotnet test --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=TestResults/coverage.opencover.xml
 
       - name: check file location
         run: find . -name '*.xml'
@@ -68,15 +68,15 @@ jobs:
       - name: Show coverage file details
         run: |
           echo "File size:"
-          stat ./AvansDevOpsTest/TestResults/coverage.cobertura.xml || echo "File not found"
+          stat ./AvansDevOpsTest/TestResults/coverage.opencover.xml || echo "File not found"
           echo "File contents:"
-          cat ./AvansDevOpsTest/TestResults/coverage.cobertura.xml || echo "No contents"
+          cat ./AvansDevOpsTest/TestResults/coverage.opencover.xml || echo "No contents"
   
       - name: Upload Coverage Artifact
         uses: actions/upload-artifact@v4
         with:
           name: coverage-report
-          path: ./AvansDevOpsTest/TestResults/coverage.cobertura.xml
+          path: ./AvansDevOpsTest/TestResults/coverage.opencover.xml
 
   sonarcloud:
     runs-on: ubuntu-latest
@@ -105,7 +105,7 @@ jobs:
             /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
             /o:wesselkuijstermans-1 \
             /d:sonar.host.url="https://sonarcloud.io" \
-            /d:sonar.coverageReportPaths=coverage/coverage.cobertura.xml
+            /d:sonar.coverageReportPaths=coverage/coverage.opencover.xml
           dotnet build ./AvansDevOps/AvansDevOps.sln --no-incremental
           dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
         env:
